apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-archival
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-archival
            image: cron-archival:latest
          restartPolicy: OnFailure
