apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: my-cronjob
  name: my-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: my-cronjob
        spec:
          containers:
          - name: cron-archival
            image: cron-archival:latest
          restartPolicy: OnFailure
